# Generated by Django 5.1.1 on 2024-09-17 15:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_img",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Makale Fotoğrafı"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="İçerik"),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturma_Tarihi"
            ),
        ),
    ]
