# Generated by Django 5.1.1 on 2024-09-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_article_article_img_alter_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Onaylı Mı"),
        ),
    ]
